import mongoose from 'mongoose';
import { RETENTION_MS } from '../retention/policy.js';

/**
 * Raw pageview event. One document per view.
 * Aggregated on read (see routes/analytics.js) so new charts don't need a migration.
 * Documents self-delete via the TTL index declared in migrations/m0/indexPlan.js —
 * the runtime connects with autoIndex=false, so indexes here are documentation only
 * and are actually created by `npm run db:m0:audit -- --apply-indexes`.
 */
export const RETENTION_DAYS = RETENTION_MS.analytics / (24 * 60 * 60 * 1000);

const pageVisitSchema = new mongoose.Schema({
    // First-party identifiers generated by the browser (localStorage / sessionStorage)
    visitorId: { type: String, required: true, index: true },
    sessionId: { type: String, required: true },
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },

    path: { type: String, required: true },
    title: { type: String, default: '' },

    // Acquisition
    referrer: { type: String, default: '' },
    referrerHost: { type: String, default: '' },
    channel: { type: String, default: 'direct', index: true },
    utmSource: { type: String, default: '' },
    utmMedium: { type: String, default: '' },
    utmCampaign: { type: String, default: '' },
    utmContent: { type: String, default: '' },
    utmTerm: { type: String, default: '' },
    gclid: { type: String, default: '' },

    // Client
    device: { type: String, default: 'desktop' },
    browser: { type: String, default: 'other' },
    os: { type: String, default: 'other' },
    language: { type: String, default: '' },
    screenWidth: { type: Number, default: 0 },

    isNewVisitor: { type: Boolean, default: false },
    isSessionStart: { type: Boolean, default: false },

    createdAt: { type: Date, default: Date.now },
}, { versionKey: false });

pageVisitSchema.index({ createdAt: -1 });
pageVisitSchema.index({ path: 1, createdAt: -1 });
pageVisitSchema.index({ sessionId: 1, createdAt: 1 });
pageVisitSchema.index({ createdAt: 1 }, { expireAfterSeconds: RETENTION_MS.analytics / 1000 });

export default mongoose.model('PageVisit', pageVisitSchema);
